### ISSUE TITLE
Load from URL not working?

### ISSUE THREAD

**Issue by XxHiroTTVxX** [Flow-Works/FlowOS#140]
no changes happen when you try to load from url

**Comment by ThinLiquid** [comment]
Does the URL contain JSON data...

**Comment by XxHiroTTVxX** [comment]
it should like a manifest.json or does it have to be custom for flowOS

**Comment by TheOneFrFr** [comment]
I have experienced a similar issue where the page doesn't load after the first time I used it. Even when I try to access it through typing in the link, it still doesn't work.
