### ISSUE TITLE
Cannot open the css editor.

### ISSUE THREAD

**Issue by Person-Who-Exists** [Flow-Works/FlowOS#142]
When I click the css editor button in the settings, it never opens.
Also after I click the button, there is a weird effect that appears on the border of the settings window when I move it around.

Here is an example of what the weird border effect looks like.
![image](https://github.com/Flow-Works/FlowOS/assets/123006012/30095dca-c6fa-4f3e-a144-a33f8d43467d)

Some notes: 
I am running on a jacuzzi boarded chromebook with goguardian disabled (don't ask me how).

Note:
The weird glowing always happens on all the different windows, seemingly only on the bottom and right edges.
Note 2:
Your website at https://flowos-thinliquid.webapp-store.de/ is down in the US.
Note 3:
The main site of flow-works.me is down at the time of 11:10

**Comment by nva-sec** [comment]
Fixed as of now.
