### ISSUE TITLE
Gambling

### ISSUE THREAD

**Issue by JeromeIsInvesting** [Flow-Works/FlowOS#166]
My feature is not related to a problem, but we need gambling. As someone who actively uses the website 24/7 and has over 1000 hours on it. I believe gambling would be an essential aspect to the website.

I would like for gambling games to be added to the website, giving users using the website the option to go against each other in gambling games.

Alternatives and more ideas are community servers integrated into the website, this would add happiness and the website would gain notoriety among the community for being a aesthetic and professionally made website.   

Additional content can have an made up currency that can give users on the website a reason for gambling. 

P.S. - Please add a community server where members and users of the website can talk and share ideas that will help the website grow and flourish. This will also grow the community. 

Thank You.

**Comment by httphypixelnet** [comment]
This project is geared towards minors - I severely doubt a gambling feature would be a good thing.

**Comment by Xanderplayz16** [comment]
Nice troll post - I see this account has only 1 repo and was made 13 hours ago.

**Comment by ThinLiquid** [comment]
> 

they're my friends at school (a lil bit annoying)

**Comment by JeromeIsInvesting** [comment]
> This project is geared towards minors - I severely doubt a gambling feature would be a good thing.

I understand the concern of gambling, but many other games/websites "geared towards minors" implement gambling inside of their games. Gambling gives more purpose, and with a currency, you can take the opportunity to "milk the minors" so to speak.

Thank You.

**Comment by JeromeIsInvesting** [comment]
> Nice joke post - I see this account has only 1 repo and was made 13 hours ago.

"Joke Post", I am simply asking for a feature to be added, does that sound like a joke? I have also been using the website for a couple months now, so I am obviously not having a joke or a laugh. This post is not a joke, nor will it ever be, it is a serious topic that will be taken seriously.
